# Generated by Django 5.2.4 on 2025-09-24 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('companies', '0003_alter_company_options_and_more'),
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'created_at'], name='jobs_job_is_acti_745178_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-created_at'], name='jobs_job_created_77460a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'is_active'], name='jobs_job_company_11c594_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type', 'is_active'], name='jobs_job_job_typ_c14aee_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location', 'is_active'], name='jobs_job_locatio_073146_idx'),
        ),
    ]
