# Generated by Django 5.2.4 on 2025-09-24 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['location'], name='companies_c_locatio_ec810c_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['location', 'created_at'], name='companies_c_locatio_8d187d_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='companies_c_created_301a54_idx'),
        ),
    ]
